#
# In order to use the application please create an application.yml in resources with these details completed
#
# Bookatable properties specifing locale settings
#bookatable:
#  dataCulture: GB
#  dataLanguage: en-GB
#
# Hitta properties specifing API secrets
#hitta:
#  callerId: example
#  apiKey: example